# Generated by Django 6.0.5 on 2026-05-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(db_index=True, max_length=120, verbose_name='Ключевая фраза')),
                ('title', models.CharField(max_length=220, verbose_name='Название товара')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(verbose_name='Количество отзывов')),
                ('image', models.CharField(max_length=180, verbose_name='Изображение')),
                ('product_url', models.URLField(verbose_name='Ссылка на товар')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Товар-конкурент',
                'verbose_name_plural': 'Товары-конкуренты',
                'ordering': ['search_query', 'position'],
                'constraints': [models.UniqueConstraint(fields=('search_query', 'position'), name='unique_competitor_position_per_query')],
            },
        ),
    ]
