# Generated by Django 6.0.5 on 2026-05-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfographicRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='uploads/', verbose_name='Исходное изображение')),
                ('generated_image', models.ImageField(blank=True, upload_to='generated/', verbose_name='Готовая инфографика')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('advantages', models.TextField(verbose_name='Преимущества')),
                ('layout_type', models.CharField(max_length=120, verbose_name='Вариант оформления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Инфографика',
                'verbose_name_plural': 'Инфографика',
                'ordering': ['-created_at'],
            },
        ),
    ]
