# Generated by Codex on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infographics", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="infographicrequest",
            old_name="advantages",
            new_name="keywords",
        ),
        migrations.AlterField(
            model_name="infographicrequest",
            name="keywords",
            field=models.TextField(verbose_name="Ключевые слова"),
        ),
    ]
