# Generated by Django 6.0.5 on 2026-05-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEORequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('category', models.CharField(max_length=150, verbose_name='Категория товара')),
                ('keywords', models.TextField(verbose_name='Ключевые слова')),
                ('advantages', models.TextField(verbose_name='Преимущества товара')),
                ('generated_text', models.TextField(verbose_name='Сгенерированное описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'SEO-запрос',
                'verbose_name_plural': 'SEO-запросы',
                'ordering': ['-created_at'],
            },
        ),
    ]
